language: node_js
node_js:
    - 6.10
branches:
  only:
  - master
  - dev
  - alex-ci-cd

cache:
  directories:
    - node_modules
script:
    - npm install -g serverless &
    - npm test &
    - wait
    - serverless deploy